//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.Modules.StandardValue.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StandardValueResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StandardValueResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bakabase.Modules.StandardValue.Resources.StandardValueResource", typeof(StandardValueResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_BooleanToNumber_Description {
            get {
                return ResourceManager.GetString("ConversionRule_BooleanToNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean to number.
        /// </summary>
        public static string ConversionRule_BooleanToNumber_Name {
            get {
                return ResourceManager.GetString("ConversionRule_BooleanToNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_DateWillBeLost_Description {
            get {
                return ResourceManager.GetString("ConversionRule_DateWillBeLost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date will be lost.
        /// </summary>
        public static string ConversionRule_DateWillBeLost_Name {
            get {
                return ResourceManager.GetString("ConversionRule_DateWillBeLost_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_Directly_Description {
            get {
                return ResourceManager.GetString("ConversionRule_Directly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly.
        /// </summary>
        public static string ConversionRule_Directly_Name {
            get {
                return ResourceManager.GetString("ConversionRule_Directly_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_Incompatible_Description {
            get {
                return ResourceManager.GetString("ConversionRule_Incompatible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible.
        /// </summary>
        public static string ConversionRule_Incompatible_Name {
            get {
                return ResourceManager.GetString("ConversionRule_Incompatible_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_OnlyFirstValidRemains_Description {
            get {
                return ResourceManager.GetString("ConversionRule_OnlyFirstValidRemains_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only first valid item remains.
        /// </summary>
        public static string ConversionRule_OnlyFirstValidRemains_Name {
            get {
                return ResourceManager.GetString("ConversionRule_OnlyFirstValidRemains_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_StringToDateTime_Description {
            get {
                return ResourceManager.GetString("ConversionRule_StringToDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to date time.
        /// </summary>
        public static string ConversionRule_StringToDateTime_Name {
            get {
                return ResourceManager.GetString("ConversionRule_StringToDateTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_StringToLink_Description {
            get {
                return ResourceManager.GetString("ConversionRule_StringToLink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to link.
        /// </summary>
        public static string ConversionRule_StringToLink_Name {
            get {
                return ResourceManager.GetString("ConversionRule_StringToLink_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_StringToNumber_Description {
            get {
                return ResourceManager.GetString("ConversionRule_StringToNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to number.
        /// </summary>
        public static string ConversionRule_StringToNumber_Name {
            get {
                return ResourceManager.GetString("ConversionRule_StringToNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_StringToTag_Description {
            get {
                return ResourceManager.GetString("ConversionRule_StringToTag_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to tag.
        /// </summary>
        public static string ConversionRule_StringToTag_Name {
            get {
                return ResourceManager.GetString("ConversionRule_StringToTag_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_StringToTime_Description {
            get {
                return ResourceManager.GetString("ConversionRule_StringToTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to time.
        /// </summary>
        public static string ConversionRule_StringToTime_Name {
            get {
                return ResourceManager.GetString("ConversionRule_StringToTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_TagGroupWillBeLost_Description {
            get {
                return ResourceManager.GetString("ConversionRule_TagGroupWillBeLost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag group will be lost.
        /// </summary>
        public static string ConversionRule_TagGroupWillBeLost_Name {
            get {
                return ResourceManager.GetString("ConversionRule_TagGroupWillBeLost_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_TimeToDateTime_Description {
            get {
                return ResourceManager.GetString("ConversionRule_TimeToDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to date time.
        /// </summary>
        public static string ConversionRule_TimeToDateTime_Name {
            get {
                return ResourceManager.GetString("ConversionRule_TimeToDateTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_Trim_Description {
            get {
                return ResourceManager.GetString("ConversionRule_Trim_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim.
        /// </summary>
        public static string ConversionRule_Trim_Name {
            get {
                return ResourceManager.GetString("ConversionRule_Trim_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_UrlWillBeLost_Description {
            get {
                return ResourceManager.GetString("ConversionRule_UrlWillBeLost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url will be lost.
        /// </summary>
        public static string ConversionRule_UrlWillBeLost_Name {
            get {
                return ResourceManager.GetString("ConversionRule_UrlWillBeLost_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_ValuesWillBeMerged_Description {
            get {
                return ResourceManager.GetString("ConversionRule_ValuesWillBeMerged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values will be merged.
        /// </summary>
        public static string ConversionRule_ValuesWillBeMerged_Name {
            get {
                return ResourceManager.GetString("ConversionRule_ValuesWillBeMerged_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_ValueToBoolean_Description {
            get {
                return ResourceManager.GetString("ConversionRule_ValueToBoolean_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to boolean.
        /// </summary>
        public static string ConversionRule_ValueToBoolean_Name {
            get {
                return ResourceManager.GetString("ConversionRule_ValueToBoolean_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConversionRule_ValueWillBeSplit_Description {
            get {
                return ResourceManager.GetString("ConversionRule_ValueWillBeSplit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value will be split.
        /// </summary>
        public static string ConversionRule_ValueWillBeSplit_Name {
            get {
                return ResourceManager.GetString("ConversionRule_ValueWillBeSplit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler for standard value with type:{0} is not found.
        /// </summary>
        public static string StandardValue_HandlerNotFound {
            get {
                return ResourceManager.GetString("StandardValue_HandlerNotFound", resourceCulture);
            }
        }
    }
}
