using Bakabase.Abstractions.Models.Domain.Constants;

namespace Bakabase.Abstractions.Models.Domain
{
    public record Enhancement
    {
        public int Id { get; set; }
        public int ResourceId { get; set; }
        public int EnhancerId { get; set; }
        public StandardValueType ValueType { get; set; }

        /// <summary>
        /// <see cref="EnhancementRawValue.Target"/>
        /// </summary>
        public int Target { get; set; }
        public string? DynamicTarget { get; set; }

        /// <summary>
        /// <see cref="EnhancementRawValue.Value"/>
        /// </summary>
        public object? Value { get; set; }

        public DateTime CreatedAt { get; set; }

        public int CustomPropertyValueId { get; set; }
        /// <summary>
        /// Generated by current enhancement
        /// </summary>
        public CustomPropertyValue? CustomPropertyValue { get; set; }
    }
}