<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

<ItemGroup>
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Acquisition\Bakabase.Modules.Acquisition.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Collection\Bakabase.Modules.Collection.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.AI\Bakabase.Modules.AI.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Alias\Bakabase.Modules.Alias.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Comparison\Bakabase.Modules.Comparison.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.DataCard\Bakabase.Modules.DataCard.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Presets\Bakabase.Modules.Presets.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.BulkModification\Bakabase.Modules.BulkModification.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.HealthScore\Bakabase.Modules.HealthScore.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Notification\Bakabase.Modules.Notification.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Subscription\Bakabase.Modules.Subscription.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Text\Bakabase.Modules.Text.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Workflow\Bakabase.Modules.Workflow.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Property\Bakabase.Modules.Property.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Enhancer\Bakabase.Modules.Enhancer.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.Search\Bakabase.Modules.Search.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.StandardValue\Bakabase.Modules.StandardValue.csproj" />
		<ProjectReference Include="..\..\modules\Bakabase.Modules.ThirdParty\Bakabase.Modules.ThirdParty.csproj" />
		<ProjectReference Include="..\Bakabase.InsideWorld.Models\Bakabase.InsideWorld.Models.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Drawing.Common" Version="9.0.0" />
		<PackageReference Include="System.Runtime.Caching" Version="9.0.0" />
		<PackageReference Include="MiniProfiler.AspNetCore" Version="4.3.8" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\DownloaderResource.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>DownloaderResource.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\SharedResource.zh-cn.Designer.cs">
			<DependentUpon>SharedResource.zh-cn.resx</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
		<Compile Update="Resources\SharedResource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>SharedResource.resx</DependentUpon>
		</Compile>
		<Compile Update="Components\Downloader\Resources\DownloaderResource.zh-Hans.Designer.cs">
			<DependentUpon>DownloaderResource.zh-Hans.resx</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\SharedResource.zh-Hans.resx">
			<LastGenOutput>SharedResource.zh-cn.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\SharedResource.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>SharedResource.Designer.cs</LastGenOutput>
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\DownloaderResource.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>DownloaderResource.Designer.cs</LastGenOutput>
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\DownloaderResource.zh-Hans.resx">
		  <LastGenOutput>DownloaderResource.zh-Hans.Designer.cs</LastGenOutput>
		  <Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Components\Downloader\Resources\" />
	  <Folder Include="Components\PostParser\Models\Domain\Constants\" />
	  <Folder Include="Components\ThirdParty\" />
	</ItemGroup>


</Project>