//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.InsideWorld.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bakabase.InsideWorld.Business.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component with type [{0}] has not been configured for category [{1}].
        /// </summary>
        internal static string Category_ComponentWithTypeHasNotBeenConfigured {
            get {
                return ResourceManager.GetString("Category_ComponentWithTypeHasNotBeenConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid categories: {0}.
        /// </summary>
        internal static string Category_Invalid {
            get {
                return ResourceManager.GetString("Category_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category can not be deleted when its media libraries exists.
        /// </summary>
        internal static string Category_MediaLibraryExistsOnDeletion {
            get {
                return ResourceManager.GetString("Category_MediaLibraryExistsOnDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate components are found: {0}.
        /// </summary>
        internal static string Component_DuplicatesAreFound {
            get {
                return ResourceManager.GetString("Component_DuplicatesAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component [{0}] is invalid.
        /// </summary>
        internal static string Component_Invalid {
            get {
                return ResourceManager.GetString("Component_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key of component can not be empty.
        /// </summary>
        internal static string Component_KeyCanNotBeEmpty {
            get {
                return ResourceManager.GetString("Component_KeyCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component can not be deleted if it is being used by categories: {0}.
        /// </summary>
        internal static string Component_NotDeletableWhenUsingByCategories {
            get {
                return ResourceManager.GetString("Component_NotDeletableWhenUsingByCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options can not be applied to [{0}] type component [{1}].
        /// </summary>
        internal static string Component_OptionsAppliedToWrongTypeDescriptor {
            get {
                return ResourceManager.GetString("Component_OptionsAppliedToWrongTypeDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options of component [{0}] are not configured.
        /// </summary>
        internal static string Component_OptionsAreNotConfigured {
            get {
                return ResourceManager.GetString("Component_OptionsAreNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options with id [{0}] are not found.
        /// </summary>
        internal static string Component_OptionsWithIdAreNotFound {
            get {
                return ResourceManager.GetString("Component_OptionsWithIdAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type wanted: [{0}], but got [{1}] from [{2}].
        /// </summary>
        internal static string Component_TypeMismatch {
            get {
                return ResourceManager.GetString("Component_TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate cookie. Requested url: {0}, message: {1}, content: {2}.
        /// </summary>
        internal static string CookieValidation_Fail {
            get {
                return ResourceManager.GetString("CookieValidation_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor for property with type:{0} is not found.
        /// </summary>
        internal static string CustomProperty_DescriptorNotFound {
            get {
                return ResourceManager.GetString("CustomProperty_DescriptorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get mid from cookie, please make sure cookie is correct.
        /// </summary>
        internal static string Downloader_BilibiliCookieIsInvalid {
            get {
                return ResourceManager.GetString("Downloader_BilibiliCookieIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili favorites is missing.
        /// </summary>
        internal static string Downloader_BilibiliFavoritesIsMissing {
            get {
                return ResourceManager.GetString("Downloader_BilibiliFavoritesIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader limits exceeded, [{0}] downloader is being used by other task(s) [{1}].
        /// </summary>
        internal static string Downloader_DownloaderCountExceeded {
            get {
                return ResourceManager.GetString("Downloader_DownloaderCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader options validator is registered for third party {0}:{1}.
        /// </summary>
        internal static string Downloader_DownloaderOptionsValidatorNotRegistered {
            get {
                return ResourceManager.GetString("Downloader_DownloaderOptionsValidatorNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start [{0}]: {1}.
        /// </summary>
        internal static string Downloader_FailedToStart {
            get {
                return ResourceManager.GetString("Downloader_FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is missing.
        /// </summary>
        internal static string Downloader_KeyIsMissing {
            get {
                return ResourceManager.GetString("Downloader_KeyIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following tasks may exist: {0}, sure to create?.
        /// </summary>
        internal static string Downloader_MayBeDuplicate {
            get {
                return ResourceManager.GetString("Downloader_MayBeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown third party id: {0}.
        /// </summary>
        internal static string Downloader_UnknownThirdPartyId {
            get {
                return ResourceManager.GetString("Downloader_UnknownThirdPartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type: {0}.
        /// </summary>
        internal static string Downloader_UnknownType {
            get {
                return ResourceManager.GetString("Downloader_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze a filename similar to [(20)191202][Publisher1(Publisher2,Publisher3),Publisher4(Publisher5),Publisher6]Title Part 2(Original)[CN].
        /// </summary>
        internal static string Enhancer_Bakabase_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakabase.
        /// </summary>
        internal static string Enhancer_Bakabase_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main language of the resource.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_Language_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_Language_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Language_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the resource.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_Name_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original works of the resource.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_Originals_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Originals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers of the resource.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_Publisher_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Publisher_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher(s).
        /// </summary>
        internal static string Enhancer_Bakabase_Target_Publisher_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Publisher_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date of the resource.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_ReleaseDt_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_ReleaseDt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_ReleaseDt_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_ReleaseDt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume name of the resource, such as &apos;episode 1&apos;.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_VolumeName_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume name.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_VolumeName_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume title of the resource, such as &apos;The beginning of the story&apos;.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_VolumeTitle_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeTitle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume title.
        /// </summary>
        internal static string Enhancer_Bakabase_Target_VolumeTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeTitle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Enhancer_Bangumi_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangumi.
        /// </summary>
        internal static string Enhancer_Bangumi_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        internal static string Enhancer_Bangumi_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Cover_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string Enhancer_Bangumi_Target_Introduction_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Introduction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Enhancer_Bangumi_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other properties in left panel.
        /// </summary>
        internal static string Enhancer_Bangumi_Target_OtherPropertiesInLeftPanel_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_OtherPropertiesInLeftPanel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating(0~10).
        /// </summary>
        internal static string Enhancer_Bangumi_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Rating_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Enhancer_Bangumi_Target_Tags_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Tags_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Cookie of ExHentai must be set in system configurations.
        ///2. The first item of search result will be treated as matched resource.
        ///3. You can set excluding tags also..
        /// </summary>
        internal static string Enhancer_ExHentai_Description {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExHentai.
        /// </summary>
        internal static string Enhancer_ExHentai_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        internal static string Enhancer_ExHentai_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Cover_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string Enhancer_ExHentai_Target_Introduction_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Introduction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Enhancer_ExHentai_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating(0~5).
        /// </summary>
        internal static string Enhancer_ExHentai_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Rating_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Enhancer_ExHentai_Target_Tags_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Tags_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist in {1}.
        /// </summary>
        internal static string FileDoesNotExistInPath {
            get {
                return ResourceManager.GetString("FileDoesNotExistInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate sources are found: {0}.
        /// </summary>
        internal static string FileMover_DuplicateSourcesAreFound {
            get {
                return ResourceManager.GetString("FileMover_DuplicateSourcesAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate targets are found: {0}.
        /// </summary>
        internal static string FileMover_DuplicateTargetsAreFound {
            get {
                return ResourceManager.GetString("FileMover_DuplicateTargetsAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources can not be sub path of sources: {0}.
        /// </summary>
        internal static string FileMover_SourcesCantBeSubOfSources {
            get {
                return ResourceManager.GetString("FileMover_SourcesCantBeSubOfSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets can not be sub path of sources: {0}.
        /// </summary>
        internal static string FileMover_TargetsCantBeSubOfSources {
            get {
                return ResourceManager.GetString("FileMover_TargetsCantBeSubOfSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not exist in {1}.
        /// </summary>
        internal static string FilesDoNotExistInPath {
            get {
                return ResourceManager.GetString("FilesDoNotExistInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Cover {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomProperty.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_CustomProperty {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_CustomProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Favorites {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Language {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Name {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Original {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Publisher {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDt.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_ReleaseDt {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_ReleaseDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Series {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Tag {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolumeIndex.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Volume_Index {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Volume_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolumeName.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Volume_Name {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Volume_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolumeTitle.
        /// </summary>
        internal static string Migration_V190_DefaultPropertyName_Volume_Title {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Volume_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found.
        /// </summary>
        internal static string PathIsNotFound {
            get {
                return ResourceManager.GetString("PathIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths should be in same directory.
        /// </summary>
        internal static string PathsShouldBeInSameDirectory {
            get {
                return ResourceManager.GetString("PathsShouldBeInSameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover file can not be saved to resource directory for single-file-resource.
        /// </summary>
        internal static string Resource_CannotSaveCoverToCurrentDirectoryForSingleFileResource {
            get {
                return ResourceManager.GetString("Resource_CannotSaveCoverToCurrentDirectoryForSingleFileResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cover must be stored in a directory.
        /// </summary>
        internal static string Resource_CoverMustBeInDirectory {
            get {
                return ResourceManager.GetString("Resource_CoverMustBeInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} to {1}.
        /// </summary>
        internal static string Resource_MovingTaskSummary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to {0}.
        /// </summary>
        internal static string Resource_MovingTaskSummaryForSingleResource {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryForSingleResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to media library {0}:{1}.
        /// </summary>
        internal static string Resource_MovingTaskSummaryForSingleResourceWithMediaLibrary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryForSingleResourceWithMediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} to media library {1}:{2}.
        /// </summary>
        internal static string Resource_MovingTaskSummaryWithMediaLibrary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryWithMediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource with id:{0} is not found.
        /// </summary>
        internal static string Resource_NotFound {
            get {
                return ResourceManager.GetString("Resource_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler for standard value with type:{0} is not found.
        /// </summary>
        internal static string StandardValue_HandlerNotFound {
            get {
                return ResourceManager.GetString("StandardValue_HandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not found.
        /// </summary>
        internal static string TypeIsNotFound {
            get {
                return ResourceManager.GetString("TypeIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not set.
        /// </summary>
        internal static string ValueIsNotSet {
            get {
                return ResourceManager.GetString("ValueIsNotSet", resourceCulture);
            }
        }
    }
}
