//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.Modules.Enhancer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnhancerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnhancerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bakabase.Modules.Enhancer.Resources.EnhancerResource", typeof(EnhancerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze a filename similar to [(20)191202][Publisher1(Publisher2,Publisher3),Publisher4(Publisher5),Publisher6]Title Part 2(Original)[CN].
        /// </summary>
        public static string Enhancer_Bakabase_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakabase.
        /// </summary>
        public static string Enhancer_Bakabase_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string Enhancer_Bakabase_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Cover_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main language of the resource.
        /// </summary>
        public static string Enhancer_Bakabase_Target_Language_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Enhancer_Bakabase_Target_Language_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Language_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the resource.
        /// </summary>
        public static string Enhancer_Bakabase_Target_Name_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Enhancer_Bakabase_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original works of the resource.
        /// </summary>
        public static string Enhancer_Bakabase_Target_Originals_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Originals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originals.
        /// </summary>
        public static string Enhancer_Bakabase_Target_Originals_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Originals_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers of the resource.
        /// </summary>
        public static string Enhancer_Bakabase_Target_Publisher_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Publisher_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher(s).
        /// </summary>
        public static string Enhancer_Bakabase_Target_Publisher_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Publisher_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date of the resource.
        /// </summary>
        public static string Enhancer_Bakabase_Target_ReleaseDt_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_ReleaseDt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string Enhancer_Bakabase_Target_ReleaseDt_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_ReleaseDt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume name of the resource, such as &apos;episode 1&apos;.
        /// </summary>
        public static string Enhancer_Bakabase_Target_VolumeName_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume name.
        /// </summary>
        public static string Enhancer_Bakabase_Target_VolumeName_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume title of the resource, such as &apos;The beginning of the story&apos;.
        /// </summary>
        public static string Enhancer_Bakabase_Target_VolumeTitle_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeTitle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume title.
        /// </summary>
        public static string Enhancer_Bakabase_Target_VolumeTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeTitle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangumi.
        /// </summary>
        public static string Enhancer_Bangumi_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string Enhancer_Bangumi_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Cover_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Enhancer_Bangumi_Target_Introduction_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Introduction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Enhancer_Bangumi_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other properties in left panel.
        /// </summary>
        public static string Enhancer_Bangumi_Target_OtherPropertiesInLeftPanel_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_OtherPropertiesInLeftPanel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be scaled correspoding the range of target rating property.
        /// </summary>
        public static string Enhancer_Bangumi_Target_Rating_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Rating_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating(0~10).
        /// </summary>
        public static string Enhancer_Bangumi_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Rating_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Enhancer_Bangumi_Target_Tags_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Tags_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLsite.
        /// </summary>
        public static string Enhancer_DLsite_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string Enhancer_DLsite_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_Cover_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Enhancer_DLsite_Target_Introduction_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_Introduction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Enhancer_DLsite_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties on the right side of cover.
        /// </summary>
        public static string Enhancer_DLsite_Target_PropertiesOnTheRightSideOfCover_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_PropertiesOnTheRightSideOfCover_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Enhancer_DLsite_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_Rating_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. You must first set the ExHentai cookie in the system settings.
        ///2. The first resource from the search results will be used as the target resource.
        ///3. You can also specify which tags to exclude..
        /// </summary>
        public static string Enhancer_ExHentai_Description {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExHentai.
        /// </summary>
        public static string Enhancer_ExHentai_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string Enhancer_ExHentai_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Cover_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Enhancer_ExHentai_Target_Introduction_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Introduction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Enhancer_ExHentai_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating(0~5).
        /// </summary>
        public static string Enhancer_ExHentai_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Rating_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Enhancer_ExHentai_Target_Tags_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Tags_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract information from file or folder name of each resource. Before you enable this enhancer, you must configure the regular expression on the configuration page..
        /// </summary>
        public static string Enhancer_Regex_Description {
            get {
                return ResourceManager.GetString("Enhancer_Regex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex expression.
        /// </summary>
        public static string Enhancer_Regex_Name {
            get {
                return ResourceManager.GetString("Enhancer_Regex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first configure the correct capture groups on the configuration page, and then enter the group names here, otherwise the enhancement will not take effect..
        /// </summary>
        public static string Enhancer_Regex_Target_CaptureGroups_Description {
            get {
                return ResourceManager.GetString("Enhancer_Regex_Target_CaptureGroups_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture groups.
        /// </summary>
        public static string Enhancer_Regex_Target_CaptureGroups_Name {
            get {
                return ResourceManager.GetString("Enhancer_Regex_Target_CaptureGroups_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property id [{0}] is not found in custom properties.
        /// </summary>
        public static string Enhancer_Target_Options_PropertyIdIsNotFoundInCustomResourceProperties {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyIdIsNotFoundInCustomResourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property id [{0}] is not found in reserved properties.
        /// </summary>
        public static string Enhancer_Target_Options_PropertyIdIsNotFoundInReservedResourceProperties {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyIdIsNotFoundInReservedResourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property id is null but property type [{0}] is not null, please reset property for target [{1}].
        /// </summary>
        public static string Enhancer_Target_Options_PropertyIdIsNullButPropertyTypeIsNot {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyIdIsNullButPropertyTypeIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type [{0}] is not supported.
        /// </summary>
        public static string Enhancer_Target_Options_PropertyTypeIsNotSupported {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type is null but property id [{0}] is not null, please reset property for target [{1}].
        /// </summary>
        public static string Enhancer_Target_Options_PropertyTypeIsNullButPropertyIdIsNot {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyTypeIsNullButPropertyIdIsNot", resourceCulture);
            }
        }
    }
}
