//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.Modules.Property.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bakabase.Modules.Property.Resources.PropertyResource", typeof(PropertyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string BuiltinPropertyName_Category {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        internal static string BuiltinPropertyName_Cover {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string BuiltinPropertyName_CreatedAt {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom property.
        /// </summary>
        internal static string BuiltinPropertyName_CustomProperty {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_CustomProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path.
        /// </summary>
        internal static string BuiltinPropertyName_DirectoryPath {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File created at.
        /// </summary>
        internal static string BuiltinPropertyName_FileCreatedAt {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_FileCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File modified at.
        /// </summary>
        internal static string BuiltinPropertyName_FileModifiedAt {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_FileModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string BuiltinPropertyName_Filename {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string BuiltinPropertyName_Introduction {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media library.
        /// </summary>
        internal static string BuiltinPropertyName_MediaLibrary {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_MediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent resource.
        /// </summary>
        internal static string BuiltinPropertyName_ParentResource {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_ParentResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string BuiltinPropertyName_Rating {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string BuiltinPropertyName_Resource {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root path.
        /// </summary>
        internal static string BuiltinPropertyName_RootPath {
            get {
                return ResourceManager.GetString("BuiltinPropertyName_RootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property descriptor is not found for pool: {0}, id: {1}.
        /// </summary>
        internal static string DescriptorIsNotFound {
            get {
                return ResourceManager.GetString("DescriptorIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor for property with type:{0} is not defined.
        /// </summary>
        internal static string DescriptorNotDefined {
            get {
                return ResourceManager.GetString("DescriptorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string PropertyPoolName_Custom {
            get {
                return ResourceManager.GetString("PropertyPoolName_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string PropertyPoolName_Internal {
            get {
                return ResourceManager.GetString("PropertyPoolName_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string PropertyPoolName_Reserved {
            get {
                return ResourceManager.GetString("PropertyPoolName_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string PropertyTypeName_Attachment {
            get {
                return ResourceManager.GetString("PropertyTypeName_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string PropertyTypeName_Boolean {
            get {
                return ResourceManager.GetString("PropertyTypeName_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string PropertyTypeName_Date {
            get {
                return ResourceManager.GetString("PropertyTypeName_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date time.
        /// </summary>
        internal static string PropertyTypeName_DateTime {
            get {
                return ResourceManager.GetString("PropertyTypeName_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        internal static string PropertyTypeName_Formula {
            get {
                return ResourceManager.GetString("PropertyTypeName_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string PropertyTypeName_Link {
            get {
                return ResourceManager.GetString("PropertyTypeName_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilevel.
        /// </summary>
        internal static string PropertyTypeName_Multilevel {
            get {
                return ResourceManager.GetString("PropertyTypeName_Multilevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline text.
        /// </summary>
        internal static string PropertyTypeName_MultilineText {
            get {
                return ResourceManager.GetString("PropertyTypeName_MultilineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple choice.
        /// </summary>
        internal static string PropertyTypeName_MultipleChoice {
            get {
                return ResourceManager.GetString("PropertyTypeName_MultipleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string PropertyTypeName_Number {
            get {
                return ResourceManager.GetString("PropertyTypeName_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string PropertyTypeName_Percentage {
            get {
                return ResourceManager.GetString("PropertyTypeName_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string PropertyTypeName_Rating {
            get {
                return ResourceManager.GetString("PropertyTypeName_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single choice.
        /// </summary>
        internal static string PropertyTypeName_SingleChoice {
            get {
                return ResourceManager.GetString("PropertyTypeName_SingleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single line text.
        /// </summary>
        internal static string PropertyTypeName_SingleLineText {
            get {
                return ResourceManager.GetString("PropertyTypeName_SingleLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string PropertyTypeName_Tags {
            get {
                return ResourceManager.GetString("PropertyTypeName_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string PropertyTypeName_Time {
            get {
                return ResourceManager.GetString("PropertyTypeName_Time", resourceCulture);
            }
        }
    }
}
