//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.InsideWorld.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bakabase.InsideWorld.Business.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component with type [{0}] has not been configured for category [{1}].
        /// </summary>
        internal static string Category_ComponentWithTypeHasNotBeenConfigured {
            get {
                return ResourceManager.GetString("Category_ComponentWithTypeHasNotBeenConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid categories: {0}.
        /// </summary>
        internal static string Category_Invalid {
            get {
                return ResourceManager.GetString("Category_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category can not be deleted when its media libraries exists.
        /// </summary>
        internal static string Category_MediaLibraryExistsOnDeletion {
            get {
                return ResourceManager.GetString("Category_MediaLibraryExistsOnDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate components are found: {0}.
        /// </summary>
        internal static string Component_DuplicatesAreFound {
            get {
                return ResourceManager.GetString("Component_DuplicatesAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component [{0}] is invalid.
        /// </summary>
        internal static string Component_Invalid {
            get {
                return ResourceManager.GetString("Component_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key of component can not be empty.
        /// </summary>
        internal static string Component_KeyCanNotBeEmpty {
            get {
                return ResourceManager.GetString("Component_KeyCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component can not be deleted if it is being used by categories: {0}.
        /// </summary>
        internal static string Component_NotDeletableWhenUsingByCategories {
            get {
                return ResourceManager.GetString("Component_NotDeletableWhenUsingByCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options can not be applied to [{0}] type component [{1}].
        /// </summary>
        internal static string Component_OptionsAppliedToWrongTypeDescriptor {
            get {
                return ResourceManager.GetString("Component_OptionsAppliedToWrongTypeDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options of component [{0}] are not configured.
        /// </summary>
        internal static string Component_OptionsAreNotConfigured {
            get {
                return ResourceManager.GetString("Component_OptionsAreNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options with id [{0}] are not found.
        /// </summary>
        internal static string Component_OptionsWithIdAreNotFound {
            get {
                return ResourceManager.GetString("Component_OptionsWithIdAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type wanted: [{0}], but got [{1}] from [{2}].
        /// </summary>
        internal static string Component_TypeMismatch {
            get {
                return ResourceManager.GetString("Component_TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate cookie. Requested url: {0}, message: {1}, content: {2}.
        /// </summary>
        internal static string CookieValidation_Fail {
            get {
                return ResourceManager.GetString("CookieValidation_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get mid from cookie, please make sure cookie is correct.
        /// </summary>
        internal static string Downloader_BilibiliCookieIsInvalid {
            get {
                return ResourceManager.GetString("Downloader_BilibiliCookieIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili favorites is missing.
        /// </summary>
        internal static string Downloader_BilibiliFavoritesIsMissing {
            get {
                return ResourceManager.GetString("Downloader_BilibiliFavoritesIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader limits exceeded, [{0}] downloader is being used by other task(s) [{1}].
        /// </summary>
        internal static string Downloader_DownloaderCountExceeded {
            get {
                return ResourceManager.GetString("Downloader_DownloaderCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader options validator is registered for third party {0}:{1}.
        /// </summary>
        internal static string Downloader_DownloaderOptionsValidatorNotRegistered {
            get {
                return ResourceManager.GetString("Downloader_DownloaderOptionsValidatorNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start [{0}]: {1}.
        /// </summary>
        internal static string Downloader_FailedToStart {
            get {
                return ResourceManager.GetString("Downloader_FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is missing.
        /// </summary>
        internal static string Downloader_KeyIsMissing {
            get {
                return ResourceManager.GetString("Downloader_KeyIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following tasks may exist: {0}, sure to create?.
        /// </summary>
        internal static string Downloader_MayBeDuplicate {
            get {
                return ResourceManager.GetString("Downloader_MayBeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown third party id: {0}.
        /// </summary>
        internal static string Downloader_UnknownThirdPartyId {
            get {
                return ResourceManager.GetString("Downloader_UnknownThirdPartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type: {0}.
        /// </summary>
        internal static string Downloader_UnknownType {
            get {
                return ResourceManager.GetString("Downloader_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist in {1}.
        /// </summary>
        internal static string FileDoesNotExistInPath {
            get {
                return ResourceManager.GetString("FileDoesNotExistInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate sources are found: {0}.
        /// </summary>
        internal static string FileMover_DuplicateSourcesAreFound {
            get {
                return ResourceManager.GetString("FileMover_DuplicateSourcesAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate targets are found: {0}.
        /// </summary>
        internal static string FileMover_DuplicateTargetsAreFound {
            get {
                return ResourceManager.GetString("FileMover_DuplicateTargetsAreFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources can not be sub path of sources: {0}.
        /// </summary>
        internal static string FileMover_SourcesCantBeSubOfSources {
            get {
                return ResourceManager.GetString("FileMover_SourcesCantBeSubOfSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets can not be sub path of sources: {0}.
        /// </summary>
        internal static string FileMover_TargetsCantBeSubOfSources {
            get {
                return ResourceManager.GetString("FileMover_TargetsCantBeSubOfSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not exist in {1}.
        /// </summary>
        internal static string FilesDoNotExistInPath {
            get {
                return ResourceManager.GetString("FilesDoNotExistInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found.
        /// </summary>
        internal static string PathIsNotFound {
            get {
                return ResourceManager.GetString("PathIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths should be in same directory.
        /// </summary>
        internal static string PathsShouldBeInSameDirectory {
            get {
                return ResourceManager.GetString("PathsShouldBeInSameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover file can not be saved to resource directory for single-file-resource.
        /// </summary>
        internal static string Resource_CannotSaveCoverToCurrentDirectoryForSingleFileResource {
            get {
                return ResourceManager.GetString("Resource_CannotSaveCoverToCurrentDirectoryForSingleFileResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cover must be stored in a directory.
        /// </summary>
        internal static string Resource_CoverMustBeInDirectory {
            get {
                return ResourceManager.GetString("Resource_CoverMustBeInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} to {1}.
        /// </summary>
        internal static string Resource_MovingTaskSummary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to {0}.
        /// </summary>
        internal static string Resource_MovingTaskSummaryForSingleResource {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryForSingleResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to media library {0}:{1}.
        /// </summary>
        internal static string Resource_MovingTaskSummaryForSingleResourceWithMediaLibrary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryForSingleResourceWithMediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} to media library {1}:{2}.
        /// </summary>
        internal static string Resource_MovingTaskSummaryWithMediaLibrary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryWithMediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource with id:{0} is not found.
        /// </summary>
        internal static string Resource_NotFound {
            get {
                return ResourceManager.GetString("Resource_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not found.
        /// </summary>
        internal static string TypeIsNotFound {
            get {
                return ResourceManager.GetString("TypeIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not set.
        /// </summary>
        internal static string ValueIsNotSet {
            get {
                return ResourceManager.GetString("ValueIsNotSet", resourceCulture);
            }
        }
    }
}
